version: "3.9"

services:
  main:
    image: api-main:latest
    container_name: api-main
    ports:
      - "8088:8088"
    volumes:
      - "./:/project"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - app_net
    depends_on:
      - mongo
      - redis

  nginx:
    image: nginx:stable
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./conf.d:/etc/nginx/conf.d
      - ./web/dist:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      - app_net
    depends_on:
      - main

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    environment:
      TZ: Asia/Shanghai
    networks:
      - app_net

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis_data:/data
    restart: always
    environment:
      TZ: Asia/Shanghai
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
