spring:
  profiles:
    activate:
      on-profile: docker

admin:
  password: 'qwertyuiopkjhgf'

redisson:
  singleServerConfig:
    address: redis://redis:6379

config:
  res: /root/project/res
  resBak: /root/project/resBak
  uploadDir: /root/project/upload

mongo:
  db: gmail-cloud
  host: mongo
  port: 27017